apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bar-app
  namespace: foo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: foo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: bar
    repoURL: https://github.com/vermell/gitops
    targetRevision: HEAD