apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: foo
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: foo
    repoURL: https://github.com/vermell/gitops
    targetRevision: HEAD